# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import background

from PyQt5 import QtCore, QtGui, QtWidgets
import background

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMessageBox, QApplication
from PyQt5.QtGui import QPainter, QPixmap


class RegisterPage(QWidget):
        def __init__(self, switch_page, db_manager):
                super().__init__()
                self.ui = Ui_Register()
                self.ui.setupUi(self)
                self.ui.LogInButton.clicked.connect(self.handle_register)
                self.switch_page = switch_page
                self.ui.ExitButton.clicked.connect(self.handle_exit)
                self.db_manager = db_manager

        def handle_register(self):
                username = self.ui.NameInput.text()
                password = self.ui.KeyInput.text()

                if not username or not password:
                        QMessageBox.warning(self, "Error", "Username and password cannot be empty!")
                        return

                existing_users = self.db_manager.query_data('user_info', 'user_name', username)
                if existing_users:
                        QMessageBox.warning(self, "Failed", "Registration failed, username already exists.")
                        return
                # 准备要插入的用户数据
                user_data = {
                        "user_name": username,
                        "user_password": password  # 实际应用中应加密密码
                }

                # 指定要插入的表名和数据
                if self.db_manager.insert_data('user_info', user_data):
                        QMessageBox.information(self, "Success", "Registration successful!")
                        self.switch_page('logIn')
                else:
                        QMessageBox.warning(self, "Failed", "Registration failed, perhaps the username already exists.")

        def handle_exit(self):
                # 关闭应用程序
                QApplication.quit()

        def showEvent(self, event):
                super().showEvent(event)
                self.ui.NameInput.clear()
                self.ui.KeyInput.clear()

class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1440, 696)
        Register.setStyleSheet("#Register{\n"
"border-image:url(:/background/background.png);\n"
"}\n"
"\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Register)
        self.label.setGeometry(QtCore.QRect(620, 140, 660, 80))
        palette = QtGui.QPalette()
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Register)
        self.frame.setGeometry(QtCore.QRect(705, 280, 490, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.NameInput = QtWidgets.QLineEdit(self.frame)
        self.NameInput.setGeometry(QtCore.QRect(90, 40, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NameInput.setFont(font)
        self.NameInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NameInput.setStyleSheet("QLineEdit {\n"
"    background-image: url(:/user/user.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px;  /* 根据图标宽度调整，确保文字不会覆盖图标 */\n"
"}\n"
"")
        self.NameInput.setText("")
        self.NameInput.setCursorPosition(0)
        self.NameInput.setPlaceholderText("")
        self.NameInput.setObjectName("NameInput")
        self.LogInButton = QtWidgets.QPushButton(self.frame)
        self.LogInButton.setGeometry(QtCore.QRect(90, 160, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.LogInButton.setFont(font)
        self.LogInButton.setStyleSheet("border:2px groove gray;\n"
"background-color: rgb(93, 200, 248);\n"
"border-radius:10px;padding:2px 4px;\n"
"")
        self.LogInButton.setObjectName("LogInButton")
        self.ExitButton = QtWidgets.QPushButton(self.frame)
        self.ExitButton.setGeometry(QtCore.QRect(90, 220, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("border:2px groove gray;\n"
"background-color: rgb(93, 200, 248);\n"
"border-radius:10px;padding:2px 4px;\n"
"")
        self.ExitButton.setObjectName("ExitButton")
        self.KeyInput = QtWidgets.QLineEdit(self.frame)
        self.KeyInput.setGeometry(QtCore.QRect(90, 100, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.KeyInput.setFont(font)
        self.KeyInput.setStyleSheet("QLineEdit {\n"
"    background-image: url(:/password/padlock.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; \n"
"}\n"
"")
        self.KeyInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.KeyInput.setObjectName("KeyInput")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 301, 19))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Dialog"))
        self.label.setText(_translate("Register", "Welcome"))
        self.LogInButton.setText(_translate("Register", "Register"))
        self.ExitButton.setText(_translate("Register", "Exit"))
        self.label_2.setText(_translate("Register", "Account%Password"))

